# Generated by Django 5.2.6 on 2025-09-25 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passageiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_app', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_motorista', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('penddente', 'Pendente'), ('processado', 'Processado'), ('falha', 'falha')], default='penddente', max_length=20)),
                ('data_pagamento', models.DateTimeField(auto_now_add=True)),
                ('solicitacao_carona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='passageiros.solicitacaocarona')),
            ],
        ),
    ]
