# Generated by Django 5.2.6 on 2025-09-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('PASSAGEIRO', 'Passageiro')], max_length=20),
        ),
    ]
